Autoxtion_B2C/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django import views
from Registration import views
import promotion.urls
import customer.urls
import Feedback.urls
import Appointment.urls
import api.urls
from django.conf import settings
import notifications.urls 

#handler404 = 'Registration.views.custom_404'

#if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
 #   urlpatterns += patterns('',
  #          url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
   # )


urlpatterns = [
    #url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^admin/', admin.site.urls),
    url(r'^registration/', include('Registration.urls')),
    url(r'^email/', include('password_reset.urls')),
    url(r'^CRM/',include('CRM.urls',namespace='CRM')),
    url(r'^promotion/', include(promotion.urls, namespace='promotion')),
    url(r'^customer/', include(customer.urls, namespace='customer')),
    url(r'^feedback/', include(Feedback.urls, namespace='Feedback')),
    url(r'^appointment/', include(Appointment.urls, namespace='Appointment')),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^api/', include(api.urls, namespace='api')),
    url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

CRM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
urlpatterns = [

    url(r'^$',views.index,name="index"),
    url(r'addlead/$',views.addlead,name="addlead"),
    #url(r'addlead/$',views.addlead.as_view(),name="addlead"),
    url(r'^edit/(?P<lead_id>[0-9]+)/$', views.edit_lead, name='edit_lead'),
    url(r'^change_status/(?P<lead_id>[0-9]+)/$', views.change_status, name='change_status'),
    url(r'^get_models/$', views.get_models),
    url(r'^get_mod/$', views.get_mod),
    url(r'^get_make_year/$', views.get_make_year),
    #url(r'^qualify_lead/$', views.qualify_lead,name="qualify_lead"),
    url(r'^crmcust/$', views.customer_index, name='customer_index'),
    url(r'^deleteVehicle/$',views.deleteVehicle,name="deleteVehicle"),
    url(r'^index2/(?P<d>[0-9]+)/$', views.index2,name="index2"),
    url(r'^customer_index2/(?P<d>[0-9]+)/$', views.customer_index2,name="cindex2"),
    url(r'^existing_cust/$', views.existing_cust,name="existing_cust"),
    url(r'^addVehicle/$', views.addVehicle,name="addVehicle"),
    url(r'^editVehicle/$', views.editVehicle,name="editVehicle"),
    url(r'^deleteVehicleCust/$',views.deleteVehicleCust,name="deleteVehicleCust"),
    url(r'^excelsheetimport/$',views.excelsheet,name="excelsheet"),
    url(r'^view_history/(?P<lead_id>[0-9]+)/$', views.view_history, name='view_history'),
    url(r'^customerRegistration/$', views.customer_registration, name='customer_registration'),  
    url(r'^customerdel/$', views.customer_delete,name="customerdel"), 
    url(r'^get_customerlist/(?P<user_id>[0-9]+)/(?P<from_dt>\d{4}-\d{2}-\d{2})/(?P<to_dt>\d{4}-\d{2}-\d{2})/$',  views.get_customer.as_view()),
    url(r'^get_leadlist/(?P<user_id>[0-9]+)/(?P<from_dt>\d{4}-\d{2}-\d{2})/(?P<to_dt>\d{4}-\d{2}-\d{2})/$',  views.get_leadlist.as_view()),
    url(r'^add/(?P<mem_detail>[0-9]+)$',views.add),
    url(r'^downloadExcelTemplate',views.downloadDemoTemplate,name="downloadexceltemplate"),
    url(r'^generate_credentials/$', views.generateCredentials,name="generateCredentials"),
    url(r'addCompany/$',views.addCompany,name="addCompany"),
    url(r'UpdateCompany/(?P<company_id>[0-9]+)/$',views.UpdateCompany,name="UpdateCompany"),
    url(r'^driver_delete_ajax/(?P<vehicle_id>\d+)$',views.driver_delete_ajax, name='driver_delete_ajax'),
    url(r'^edit_drivers/$',views.edit_drivers, name='edit_drivers'),
    url(r'^company_list/$', views.company_index, name='company_index'),

]

customer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
              
   url(r'^$', views.RequestList.as_view(), name='server_list'),
   #url(r'^$', views.CustomerRequestList, name='server_list'),
   url(r'^new_req/$', views.RequestnewCreate.as_view(), name='server_new_req'),
   url(r'^new/(?P<pk>\d+)$', views.RequestCreate.as_view(), name='server_new'),
   url(r'^edit/(?P<pk>\d+)$', views.RequestUpdate.as_view(), name='server_edit'),
   url(r'^delete/(?P<pk>\d+)$', views.RequestDelete.as_view(), name='server_delete'),
   url(r'^get_lead/',views.get_lead),
   #url(r'^get_promo/(?P<requestid>\d+)$',views.get_promo.as_view()),
   url(r'^memberedit/(?P<pk>\d+)$',views.MemberEditRequest.as_view(), name='member_edit_request'),
   url(r'^confirm/(?P<customer_request_id>[0-9]+)/$',views.ConfirmRequest, name='confirm_request'),
   url(r'^accept/(?P<customer_request_id>[0-9]+)/$',views.AcceptRequest, name='accept_request'),


   url(r'^customer_history/$', views.customer_history.as_view(), name='customer_history'),
   url(r'^EmergencyRequestList/$', views.EmergencyRequestList.as_view(), name='EmergencyRequestList'),
   url(r'^Add_emergency_req/$', views.Add_emergency_req.as_view(), name='Add_emergency_req'),
   url(r'^edit_emergency_req/(?P<pk>\d+)$', views.edit_emergency_req.as_view(), name='edit_emergency_req'),
   url(r'^membereditemergency/(?P<pk>\d+)$',views.MemberEditRequestEmergency.as_view(), name='member_edit_emergency'),
   url(r'^delete_emergency_req/(?P<pk>\d+)$', views.delete_emergency_req.as_view(), name='delete_emergency_req'),
   url(r'^emer_confirm/(?P<customer_request_id>[0-9]+)/$',views.Emer_ConfirmRequest, name='emer_confirm_request'),
]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])

customer/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User, Group
from promotion.models import Service
from CRM.models import Lead
from promotion.models import * 

# Create your models here.

"""class customer(models.Model):
    customer=models.OneToOneField(User)
    member= models.ForeignKey(User, on_delete=models.CASCADE)
    #group= models.ForeignKey(Group, on_delete=models.CASCADE)"""
    
class customer_request(models.Model):
    vehicle= models.ForeignKey(Lead_Vehicle, on_delete=models.CASCADE)
    service_type= models.ForeignKey(Service, on_delete=models.CASCADE)
    description=models.TextField()
    customer=models.ForeignKey(Lead, on_delete=models.CASCADE)
    promotion = models.ForeignKey(Promotions, models.DO_NOTHING, blank=True, null=True)
    date_request = models.DateField(blank=True, null=True)
    date_update = models.DateField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True)
    date = models.DateField(blank=True,null=True)
    from_time = models.CharField(max_length=11)
    to_time = models.CharField(max_length=11)
    status = models.ForeignKey(Status, models.DO_NOTHING, blank=True, null=True)
    emergency_status = models.BooleanField()
    comment=models.CharField(blank=True, null=True,max_length=300)

    def __str__(self):
         return self.description

    class Meta:
        db_table="customer_request"
        
class Accident_Request(models.Model):
    image1= models.ImageField(blank= True, null= True)
    image2= models.ImageField(blank=True, null=True)
    car_detail= models.CharField(max_length= 100, blank=True, null=True)
    location= models.CharField(max_length=100, blank= True, null=True)
    phone_no = models.CharField(max_length=10, blank= True, null=True)
    customer=models.ForeignKey(Lead, on_delete=models.CASCADE)
    date_request = models.DateField(blank=True, null=True)
    date_update = models.DateField(blank=True, null=True)
    status = models.ForeignKey(Status, models.DO_NOTHING, blank=True, null=True)
    
    def __str__(self):
        return self.location
    
    class Meta:
        db_table="customer_accident_request"

class Customer_Outsource_History(models.Model):
    member_name= models.CharField(max_length= 45, blank=True, null=True)
    shop_name= models.CharField(max_length=45, blank= True, null=True)
    phone_no = models.CharField(max_length=10, blank= True, null=True)
    date_request = models.DateField(blank=True, null=True)
    description = models.CharField(max_length=100, blank= True, null=True)
    price = models.CharField(max_length=10, blank= True, null=True)
    customer=models.ForeignKey(Lead, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.description
    
    class Meta:
        db_table="customer_outsource_history"

        
class ExpenseType(models.Model):
    expense_type = models.CharField(db_column='expense _type', max_length=45)  # Field renamed to remove unsuitable characters.
    image = models.ImageField()

    class Meta:
        managed = False
        db_table = 'customer_expense _type'
	verbose_name_plural = 'ExpenseType'
        
    def __str__(self):
        return self.expense_type

class ExpenseDetails(models.Model):
    customer = models.ForeignKey(Lead,on_delete=models.CASCADE,blank=True, null=True)
    payment_type = models.CharField(max_length=45)
    date = models.DateField()
    total = models.IntegerField()
    tax = models.CharField(max_length=45)
    expense_type = models.ForeignKey(ExpenseType,on_delete=models.CASCADE,  db_column='expense_type')
    image = models.ImageField(blank=True, null=True)
    description = models.CharField(max_length=45)

    class Meta:
        managed = False
        db_table = 'customer_expense_details'
    def __str__(self):
        return "%s" % self.id

customer/forms.py
from django import forms
from customer.models import customer_request
from promotion.models import Service
from CRM.models import *
from django.contrib.auth.models import User, Group

class customerForm(forms.ModelForm):
    vehicle=forms.ModelChoiceField(queryset=Lead_Vehicle.objects.all(),widget=forms.Select(attrs={'class':'col-md-3 form-control'}))
    date = forms.DateField(input_formats=['%d/%m/%Y'],required=False, widget=forms.widgets.DateInput(format="%d/%m/%Y"))
    from_time = forms.CharField()
    to_time = forms.CharField()
    #coment = forms.CharField(required= False, max_length=100)
    service_type=forms.ModelChoiceField(queryset=Service.objects.all(),widget=forms.Select(attrs={'class':'col-md-3 form-control'}))   
    description= forms.CharField(widget=forms.Textarea)
    image=forms.ImageField(required=False)
    comment= forms.CharField(widget=forms.Textarea,required=False)     
    class Meta:
        model = customer_request
        fields = ('date','from_time','to_time','service_type','description','image','vehicle','comment')
    def __init__(self, *args, **kwargs):
        self.users = kwargs.pop('users', None)
        print("self.users self.users", self.users)
        super(customerForm, self).__init__(*args, **kwargs)
        group=Group.objects.get(user=self.users)
        try:
            if group.name=="Company":
                company=CustCompany.objects.get(email=self.users.email)
                print("company",company)
                driver1=Company_Driver.objects.filter(company=company)
                print("driver",driver1)
                for driver in driver1:
                    lead1=Lead.objects.get(pk=driver.driver.pk)
                    l_u=lead_user.objects.get(customer=lead1)
                    print("lead vehicle ",Lead_Vehicle.objects.filter(lead=l_u.customer))
                    self.fields['vehicle'].queryset= Lead_Vehicle.objects.filter(lead=l_u.customer)
                    
            else:
                lead_u=lead_user.objects.get(user=self.users)
                print("lead_u", lead_u.customer)
                self.fields['vehicle'].queryset= Lead_Vehicle.objects.filter(lead=lead_u.customer)

        except Exception as e:
            print("exception has occured",e)

        
class UpdatecustomerForm(forms.ModelForm):
    date = forms.DateField(input_formats=['%d/%m/%Y'],required=False, widget=forms.widgets.DateInput(format="%d/%m/%Y"))
    from_time = forms.CharField()
    to_time = forms.CharField()
    #coment = forms.CharField(required= False, max_length=100)
    service_type=forms.ModelChoiceField(queryset=Service.objects.all(),widget=forms.Select(attrs={'class':'col-md-3 form-control'}))   
    description= forms.CharField()
    image=forms.ImageField(required=False)   
    class Meta:
        model = customer_request
        fields = ('date','from_time','to_time','service_type','description','image')
    def __init__(self, *args, **kwargs):
        self.users = kwargs.pop('users', None)
        super(customerForm, self).__init__(*args, **kwargs)
        group=Group.objects.get(user=self.users)
        try:
            if group.name=="Company":
                company=CustCompany.objects.get(email=self.users.email)
                print("company",company)
                driver1=Company_Driver.objects.filter(company=company)
                print("driver",driver1)
                for driver in driver1:
                    lead1=Lead.objects.get(pk=driver.driver.pk)
                    l_u=lead_user.objects.get(customer=lead1)
                    print("lead vehicle ",Lead_Vehicle.objects.filter(lead=l_u.customer))
                    self.fields['vehicle'].queryset= Lead_Vehicle.objects.filter(lead=l_u.customer)
                    
            else:
                lead_u=lead_user.objects.get(user=self.users)
                print("lead_u", lead_u.customer)
                self.fields['vehicle'].queryset= Lead_Vehicle.objects.filter(lead=lead_u.customer)

        except Exception as e:
            print("exception has occured",e)

class customerMemberEditForm(forms.ModelForm):
    vehicle=forms.ModelChoiceField(queryset=Lead_Vehicle.objects.all(),widget=forms.Select(attrs={'class':'col-md-3 form-control'}))
    date = forms.DateField(input_formats=['%d/%m/%Y'],required=False, widget=forms.widgets.DateInput(format="%d/%m/%Y"))
    from_time = forms.CharField()
    to_time = forms.CharField()
    #coment = forms.CharField(required= False, max_length=100)
    service_type=forms.ModelChoiceField(queryset=Service.objects.all(),widget=forms.Select(attrs={'class':'col-md-3 form-control'}))   
    description= forms.CharField(widget=forms.Textarea)
    image=forms.ImageField(required=False)
    comment= forms.CharField(widget=forms.Textarea,required=False)  
   
    class Meta:
        model = customer_request
        fields = ('date','from_time','to_time','service_type','description','image','vehicle','comment')


class customerRequestPromotionForm(forms.ModelForm):
    #vehicle=forms.ModelChoiceField(queryset=Lead_Vehicle.objects.all(),widget=forms.Select(attrs={'class':'col-md-3 form-control'}))
    date = forms.DateField(input_formats=['%d/%m/%Y'],required=False, widget=forms.widgets.DateInput(format="%d/%m/%Y"))
    from_time = forms.CharField()
    to_time = forms.CharField()
    #coment = forms.CharField(required= False, max_length=100)
    service_type=forms.ModelChoiceField(queryset=Service.objects.all(),widget=forms.Select(attrs={'class':'col-md-3 form-control'}))   
    description= forms.CharField(widget=forms.Textarea)
    image=forms.ImageField(required=False)   
    class Meta:
        model = customer_request
        fields = ('date','from_time','to_time','service_type','description','image')

       

customer/templates/customer/customer_request_confirm_delete.html
{% extends "base2.html" %}
{% load static from staticfiles %}
{%  block head %}
<!-- <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="all"> -->
{% endblock %}
{% load i18n %}
{% block content %}
<input type="hidden" id="group" value="{{group.name}}">


<div >
 
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">

          <h4 class="modal-title">Delete Request</h4>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this record?.</p>
        </div>
        <div class="modal-footer">
        <form method="post">{% csrf_token %}
          <button type="submit" class="btn btn-success" data-dismiss="modal">Yes</button>
      <a href="{% url 'customer:server_list'  %}"><button type="button" class="btn btn-primary" data-dismiss="modal">No</button></a>
</form>
        </div>
      </div>
    </div>
  </div>

<br><br><br><br><br><br>
{% endblock %}

customer/templates/customer/customer_updaterequest_form.html
{% extends "base2.html" %}
{% load static from staticfiles %}
{% load i18n %}

{% block head %}
<style>
.desc{
height:40px;
padding-top: 25px;
}
.page-header {
    padding-bottom: 9px;
    margin: 10px 0 20px !important;
    border-bottom: 1px solid #eee;
}
</style>

<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <script src="{% static 'js/validation/request_validation.js' %}"></script>
 <link rel="stylesheet" href="{% static 'css/wickedpicker.css' %}">  
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
 <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>  
  <script type="text/javascript" src="{% static 'js/wickedpicker.js' %}"></script>
<script type="text/javascript" src="{% static 'js/image_update.js' %}"></script>
<script type='text/javascript'>
$( document ).ready(function() {
	var hv = $('#myhidden3').val();
	var hv1 = $('#myhidden4').val();
	//alert(hv);
	//alert(hv1)
	if (hv.length<1) {
	    //alert("in if");
	    //$(select).prop('disabled',false);
	    
	}
	else{
		//alert("in else");
		$('#id_service_type').empty();
		$('#id_service_type').append("<option value="+hv+">"+hv1+"</option>");
		//$("#id_service_type").prop('disabled',true);
	}
	
    
    
});


$(function() {
    $('#id_customer').change(function() {
    	
        // if changed to, for example, the last option, then
        // $(this).find('option:selected').text() == D
        // $(this).val() == 4
        // get whatever value you want into a variable
        var x = $(this).val();
        // and update the hidden input's value
        $('#myhidden').val(x);
    });

    
   $('#id_promotion').change(function() {
    	
        // if changed to, for example, the last option, then
        // $(this).find('option:selected').text() == D
        // $(this).val() == 4
        // get whatever value you want into a variable
        var x = $(this).val();
        // and update the hidden input's value
        $('#myhidden2').val(x);
        
    });
});
</script>
<script>

$(document).ready(function(){
	//for disable fields
	console.log('function called');
	//for disable fields
	console.log('function called');
        $("#id_vehicle").prop('disabled', true);
	$("#id_service_type").prop('disabled', true);
	$("#id_description").prop('disabled', true);
	$("#id_date").prop('disabled', true);
	$("#id_from_time").prop('disabled', true);
	$("#id_to_time").prop('disabled', true);
	$("#id_image").prop('disabled', true);
	$("#id_comment").prop('disabled', true);
	$("#schedule").show();
		$("#re-schedule").show();
		$("#button_submit").hide();
	//for enable fields
	$('#re-schedule').on("click",function() {
		console.log('click function');
                $("#id_vehicle").prop('disabled', false);
		$("#id_service_type").prop('disabled', false);
		$("#id_description").prop('disabled', false);
		$("#id_image").prop('disabled', false);
		$("#id_date").prop('disabled', false);
		$("#id_from_time").prop('disabled', false);
		$("#id_to_time").prop('disabled', false);
		$("#id_comment").prop('disabled', true);
		$("#schedule").hide();
		$("#re-schedule").hide();
		$("#button_submit").show();
	});
	
	
	//for applying class to fields
	$("#id_comment").attr("class","form-control");

	//$("#id_image").attr("class","form-control");
	$("#id_customer").attr("type","hidden");
	$("#id_promotion").attr("class","form-control");
	$("#id_description").attr("class","form-control");
	$("#id_service_type").attr("class","form-control");
	$("#id_customer").attr("class","form-control");
	$("#id_date").attr("class","form-control");
	$("#id_from_time").attr("class","form-control");
	$("#id_to_time").attr("class","form-control");
	$(".data_request").attr("class","form-control");
	  $( "#id_date" ).datepicker({minDate:0,dateFormat:'dd/mm/yy'});
	    $('#id_from_time').wickedpicker();
	    $('#id_to_time').wickedpicker();
	   
	  });
       

$.ajax({
	 url:'/customer/get_lead/',
        type:"GET",
  }).done(function(data){
	console.log(data);
	   $('#myhidden').val(data.customer);
	  
});


</script>

<style>
.row{
margin-right:0px;
}
.seperator{
border-top: 4px solid #F38619;
}
.active_class{
color:#f38619;
}
.thumb-image{

height:450px;
width:450px;
}
</style>
{% endblock %}
{% block content %}
<div class="page-header">
             <h4 class="" style="color: #6B748A;font-size:17px;"><span class="glyphicon glyphicon-th-list"></span>
                  UPDATE REQUEST</h4>

        </div>
 <div class="row">   
                
          
          <div class="dropdown pull-right">
        <a href="{% url 'customer:server_list'  %}">
            <button type="button" class="btn btn-primary " data-dismiss="modal">
               <i class="fa fa-reply" aria-hidden="true">
               </i> Back</button>
           </a>
             <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown" id="save_req">
               <i class="fa fa-floppy-o"></i> Save
                <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                                             
                       <li><a  id="re-schedule"  type="submit"style="cursor: pointer;"><i class="fa fa-pencil" aria-hidden="true"></i> Edit Request</a></li>
                        <li><a  id="button_submit"   type="submit"style="cursor: pointer;"><i class="fa fa-check" aria-hidden="true"></i> Save and Exit</a></li>                       
                      {% with status=object.status.status sch="Reschedule" %}
                    	{% ifequal status sch %}
                     <li><a href="{% url 'customer:accept_request' object.id  %}" style="cursor: pointer;"><i class="fa fa-pencil" aria-hidden="true"></i> Accept</a></li>
                       {% endifequal %}{% endwith %}
                   </ul>
             </div>
        </div>
  

<input type="hidden" id="group" value="{{group.name}}">
<div class=" register">
    

<div class="row contact-upper-section ">
		{% if promo_detail %}
            <div class="col-md-7 "  >
                
                 <div class="row ">
                   	<div class="col-md-4">
                   			<strong>Company:</strong><a class="data_request" style="background-color:#f2f2f2;color:#000;">{{promo_detail.company}}</a>
					</div>
				
				
                   	<div class="col-md-4">
                   <strong>Model:</strong> <a class="data_request" style="background-color:#f2f2f2;color:#000;">{{promo_detail.model_id}}</a>
					</div>
			
				
                   	<div class="col-md-4">
                   <strong>Make year:</strong> <a class="data_request" style="background-color:#f2f2f2;color:#000;">{{promo_detail.make_year}}</a>
					</div>
				</div>
				<div class="row">
                   	<div class="col-md-4 ">
                   <strong>Discount:</strong> <a class="data_request" style="background-color:#f2f2f2;color:#000;">{{promo_detail.discount}}</a>
					</div>
				
          		
                   	<div class="col-md-4">
                   <strong>Coupon Code:</strong> <a class="data_request" style="background-color:#f2f2f2;color:#000;">{{promo_detail.coupon_code}}</a>
					</div>
				</div>
				<div class="row">
                   	<div class="col-md-4">
                   <strong>From Date:</strong> <a class="data_request" style="background-color:#f2f2f2;color:#000;">{{promo_detail.from_date}}</a>
					</div>
				
                   	<div class="col-md-4 ">
                   <strong>To Date:</strong><a class="data_request" style="background-color:#f2f2f2;color:#000;">{{promo_detail.to_date}}</a>
					</div>
				</div>
             <div class="row ">
                   	<div class="col-md-12 ">
                   <strong>Description:</strong> <a class="data_request" style="background-color:#f2f2f2;color:#000;">{{promo_detail.description}}</a>
                   
					</div>
				</div>
				<input type="hidden" name="promo_id" id="promotion_id" value="{{promo_detail.pk}}">
				
                </div>
                {% endif %}
<div class="contact-form col-sm-7 ">
               
                <form class="form-horizontal" id="request_form" action="" enctype="multipart/form-data" method="post">{% csrf_token %}

           
<div class="form-group">
				    
				            <label for="id_customer" class="control-label"></label>
        
           
                          <input id="myhidden" name="customer" type="hidden"  value="{{request.user.id}}"> 
				     
				     </div>
				 <div class="form-group">
				     
				     <label for="id_promotion" class="control-label"></label>
        
           
                          <input id="myhidden2" name="promotion" type="hidden"  value="{{promo}}"> 
				    
				      </div>


    <input id="myhidden3"  type="hidden"  value="{{promo_detail.Service_id.pk}}"> 
    <input id="myhidden45"  type="hidden"  value="{{promo_detail.Service_id}}"> 

      <div class="form-group">
			    <label class="col-md-5 col-xs-5 col-sm-5 control-label" for="id_service_type">Vehicle:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7">
                    {{form.vehicle}}<div id="error_veh"style="color:red"></div>	 
  			         <span class="help-block"> </span>  
			    </div>
			</div>

     <div class="form-group">
			    <label class="col-md-5 col-xs-5 col-sm-5 control-label" for="id_service_type">Service Type:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7">
                    {{form.service_type}}<div id="error1"style="color:red"></div>	 
  			         <span class="help-block"> </span>  
			    </div>
			</div>
     <div class="form-group">
			    <label class="col-md-5 col-xs-5 col-sm-5 control-label" for="id_date">Date:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7">
                      {{form.date}}<div id="error7"style="color:red"></div>	
 
  			         <span class="help-block"> </span>  
			    </div>
			</div>
    
	 <div class="form-group">
			    <label class="col-md-5 col-xs-5 col-sm-5 control-label" for="id_date">From time:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7">
                        {{form.from_time}}<div id="error8"style="color:red"></div>	
  			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group">
			    <label class="col-md-5 col-xs-5 col-sm-5 control-label" for="id_date">To time:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7">
                        {{form.to_time}}<div id="error9"style="color:red"></div>	
  			         <span class="help-block"> </span>  
			    </div>
			</div>
            <div class="form-group">
			    <label class="col-md-5 col-xs-5 col-sm-5 control-label" for="id_service_type">Request Description:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7">
                        {{form.description}}<div id="error2"style="color:red"></div>	
  			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group">
			    <label class="col-md-5 col-xs-5 col-sm-5 control-label" for="id_service_type">Image:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7 image_get">
                        {{form.image}}<div class="row" id="lblError" style="color: red;margin:5px 0px 5px 0px;"></div>
  			         <span class="help-block"> </span>  
			    </div>
			</div>
                          {% if form.comment %}
   		   <div class="form-group comment">
			    <label class="col-md-5 col-xs-5 col-sm-5 control-label" for="id_service_type">Comment:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7">
                    {{form.comment}}<div id="error_coment" style="color:red"></div>	 
  			         <span class="help-block"> </span>  
			    </div>
			</div>
         {% endif %}
   
        {% if object %}
        
           {% else %}
           <input class="btn btn-primary" id="promo" type="submit" value="{% trans 'Submit' %}" >
           {% endif %}       
                 
                   
                </form>
            </div>
            <div class="col-md-5">
             <div id="image-holder" style="padding-top:43px;"></div>
       
            </div>

        </div>
       
    </div>

{% endblock %}