Appointment/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.AppointmentList.as_view(), name='server_list'),
    url(r'^new/(?P<pk>\d+)$', views.AppointmentCreate.as_view(), name='server_new'),
    url(r'^edit/(?P<pk>\d+)$', views.AppointmentUpdate.as_view(), name='server_edit'),
    url(r'^delete/(?P<pk>\d+)$', views.AppointmentDelete.as_view(), name='server_delete'),
    url(r'^app_done/(?P<pk>\d+)$', views.done_appointment, name='server_done'),

    url(r'^upcell_app_add/(?P<appointment_id>\d+)$', views.Upcell_app_add, name='upcell_app_add'),
    url(r'^upcell_app_update/(?P<appointment_id>\d+)$', views.upcell_app_update, name='upcell_app_update'),
    url(r'^customer_upcell_update/(?P<appointment_id>\d+)$', views.customer_upcell_update, name='customer_upcell_update'),
    url(r'^member_view_upcell_accepted/(?P<appointment_id>\d+)$', views.member_view_upcell_accepted, name='member_view_upcell_accepted'),
    url(r'^upcell_delete_ajax/(?P<upcell>\d+)$',views.upcell_delete_ajax, name='upcell_delete_ajax'),
    url(r'^appointment_history/$', views.appointment_history, name='appointment_history'),
    url(r'^subservice_ajax/$',views.subservice_ajax, name='subservice_ajax'),  
    url(r'^schedule_appointment/(?P<pk>\d+)$',views.schedule_appointment, name='schedule_appointment'),
    url(r'^create/$', views.member_create_appointment, name='member_create_appointment'),
    url(r'^get_leads/$',views.ajxviews,name='get_leads'),
    url(r'^today_appointment_list/$', views.today_appointment_list.as_view(), name='today_appointment_list'),
    url(r'^appointment_history_detail/(?P<appointment_id>[0-9]+)/$', views.Appointment_History_Detail, name='appointment_history_detail'),
    url(r'^get_vehicle/$', views.get_vehicle, name='get_vehicle'),
]

CRM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
urlpatterns = [

    url(r'^$',views.index,name="index"),
    url(r'addlead/$',views.addlead,name="addlead"),
    #url(r'addlead/$',views.addlead.as_view(),name="addlead"),
    url(r'^edit/(?P<lead_id>[0-9]+)/$', views.edit_lead, name='edit_lead'),
    url(r'^change_status/(?P<lead_id>[0-9]+)/$', views.change_status, name='change_status'),
    url(r'^get_models/$', views.get_models),
    url(r'^get_mod/$', views.get_mod),
    url(r'^get_make_year/$', views.get_make_year),
    #url(r'^qualify_lead/$', views.qualify_lead,name="qualify_lead"),
    url(r'^crmcust/$', views.customer_index, name='customer_index'),
    url(r'^deleteVehicle/$',views.deleteVehicle,name="deleteVehicle"),
    url(r'^index2/(?P<d>[0-9]+)/$', views.index2,name="index2"),
    url(r'^customer_index2/(?P<d>[0-9]+)/$', views.customer_index2,name="cindex2"),
    url(r'^existing_cust/$', views.existing_cust,name="existing_cust"),
    url(r'^addVehicle/$', views.addVehicle,name="addVehicle"),
    url(r'^editVehicle/$', views.editVehicle,name="editVehicle"),
    url(r'^deleteVehicleCust/$',views.deleteVehicleCust,name="deleteVehicleCust"),
    url(r'^excelsheetimport/$',views.excelsheet,name="excelsheet"),
    url(r'^view_history/(?P<lead_id>[0-9]+)/$', views.view_history, name='view_history'),
    url(r'^customerRegistration/$', views.customer_registration, name='customer_registration'),  
    url(r'^customerdel/$', views.customer_delete,name="customerdel"), 
    url(r'^get_customerlist/(?P<user_id>[0-9]+)/(?P<from_dt>\d{4}-\d{2}-\d{2})/(?P<to_dt>\d{4}-\d{2}-\d{2})/$',  views.get_customer.as_view()),
    url(r'^get_leadlist/(?P<user_id>[0-9]+)/(?P<from_dt>\d{4}-\d{2}-\d{2})/(?P<to_dt>\d{4}-\d{2}-\d{2})/$',  views.get_leadlist.as_view()),
    url(r'^add/(?P<mem_detail>[0-9]+)$',views.add),
    url(r'^downloadExcelTemplate',views.downloadDemoTemplate,name="downloadexceltemplate"),
    url(r'^generate_credentials/$', views.generateCredentials,name="generateCredentials"),
    url(r'addCompany/$',views.addCompany,name="addCompany"),
    url(r'UpdateCompany/(?P<company_id>[0-9]+)/$',views.UpdateCompany,name="UpdateCompany"),
    url(r'^driver_delete_ajax/(?P<vehicle_id>\d+)$',views.driver_delete_ajax, name='driver_delete_ajax'),
    url(r'^edit_drivers/$',views.edit_drivers, name='edit_drivers'),
    url(r'^company_list/$', views.company_index, name='company_index'),

]

Appointment/models.py
from __future__ import unicode_literals
from django.db import models
from CRM.models import Lead, Status
from customer.models import customer_request
from Registration.models import UserProfile
from promotion.models import *

# Create your models here.

class MemberAppointment(models.Model):
    vehicle= models.ForeignKey(Lead_Vehicle, on_delete=models.CASCADE)
    customer = models.ForeignKey(Lead, models.DO_NOTHING, blank=True, null=True)
    member = models.ForeignKey(UserProfile, models.DO_NOTHING, blank=True, null=True)
    request = models.ForeignKey(customer_request, models.DO_NOTHING, blank=True, null=True)
    status = models.ForeignKey(Status, models.DO_NOTHING, blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    from_time= models.CharField(max_length=11)
    to_time= models.CharField(max_length=11)
    date_appointment = models.DateField(blank=True, null=True)
    date_update = models.DateField(blank=True, null=True)
    coment= models.CharField(max_length=255, blank=True, null=True)
    totalamount= models.FloatField(max_length=45, blank=True, null=True)
    service_type=models.ForeignKey(Service,models.DO_NOTHING, blank=True, null=True)
    upcell_status= models.CharField(max_length=45, blank=True, null=True)

   
    class Meta:
        managed = False
        db_table = 'member_appointment'

class SubServiceType(models.Model):
 
    service_type_name = models.CharField(max_length=45, blank=True, null=True)
    service = models.ForeignKey(Service, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'sub_service_type'
        
    def __str__(self):
        return self.service_type_name
        
class UpcellAppointment(models.Model):
    
    appointment = models.ForeignKey(MemberAppointment,blank=True, null=True)
    service = models.ForeignKey(Service)
    sub_service = models.ManyToManyField(SubServiceType)
    amount = models.FloatField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    description= models.CharField(max_length=255, blank=True, null=True)
    accept = models.BooleanField()
    image= models.ImageField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'upcell_appointment'


class UpcellAppointmentSubService(models.Model):
    upcellappointment = models.ForeignKey(UpcellAppointment, blank=True, null=True)
    subservicetype = models.ForeignKey(SubServiceType, blank=True, null=True)
    

    class Meta:
        managed = False
        db_table = 'upcell_appointment_sub_service'

Appointment/views.py
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.template.context import RequestContext
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.core.urlresolvers import reverse_lazy
from Appointment.models import *
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User, Group
from CRM.models import *
import logging
logger = logging.getLogger('Appointment')
logger.addHandler(logging.NullHandler())
from customer.models import *
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string, get_template
from django.template import Context
from datetime import datetime
from promotion.mixin import *
from django.template.response import TemplateResponse
from django.contrib.messages.views import SuccessMessageMixin
from notifications.signals import notify
from .tasks import *
from django.db.models import Q
from.forms import *
from django.core.urlresolvers import reverse
from django.forms import formset_factory
from django.db.models import Sum
from django.http import JsonResponse
# Create your views here.
from django.forms.models import model_to_dict
from push_notifications.models import  APNSDevice
from fcm_django.models import FCMDevice
from django.forms.models import modelformset_factory
from Timeline.models import *
from django.utils import timezone
from Appointment.filters import *
from django.contrib import messages
from django.http.response import HttpResponse, HttpResponseRedirect
    
class AppointmentList(AuthRequiredMixin, ListView):
    model= MemberAppointment
    template_name = 'Appointment/Appointment_list.html'
    success_url = reverse_lazy('promotion:server_list')
    
    def get_context_data(self, **kwargs):
        context = super(AppointmentList, self).get_context_data(**kwargs)
        response = TemplateResponse(self.request, self.template_name)
        user = self.request.user
        group=Group.objects.get(user=user)
        if group.name == "Member":
            logger.debug("user is member")
            #profile=UserProfile.objects.get(user=user)
            #var2=MemberAppointment.objects.filter(member=profile,)
            status=Status.objects.get(status="Job Completed")
            profile=UserProfile.objects.get(user=user)
            var2=MemberAppointment.objects.filter(~Q(status=status),member=profile)
            today=datetime.today()
            date=today.date()
            filter = AppointmentFilter(self.request.GET, queryset=var2)
            context['filter'] = filter
            context['object_list'] = var2
            context['group'] = group
            #context['today'] = date
            return context
        elif group.name == "Company":
            logger.debug("user is company")
            company_auth=User.objects.get(email=user.email)
            cust_comp=CustCompany.objects.get(email=company_auth.email)
            print("customer company:",cust_comp.email)
            status=Status.objects.get(status="Job Completed")
            comp_dri=Company_Driver.objects.filter(company=cust_comp)
            print("before for")
            for comp_driver in comp_dri:
                print(" after for company driver",comp_driver)
                #status=Status.objects.get(status="Job Completed")
                #var2=MemberAppointment.objects.filter(~Q(status=status),customer=comp_driver.driver)
                var2=MemberAppointment.objects.filter(~Q(status=status),customer__in=[comp_driver.driver for comp_driver in comp_dri ])
                print("sorted member appointment:",var2)
                today=datetime.today()
                date=today.date()
                filter = AppointmentFilter(self.request.GET, queryset=var2)
                context={'filter':filter,'today':date,'group': group,'object_list':var2}
                return context
        else:
            logger.debug("user is customer")
            customer=lead_user.objects.get(user=user)
            var1 = Lead.objects.get(pk=customer.customer.pk)
            address= UserProfile.objects.get(user=var1.member) 
            var2= MemberAppointment.objects.filter(customer=customer.customer)
            today=datetime.today()
            date=today.date()
            cust = Lead.objects.get(pk=customer.customer.pk) 
            filter = AppointmentFilter(self.request.GET, queryset=var2)
            context = {'object_list': var2, 'group': group, 'address': address, 'today': date,'filter':filter}            
            context['object_list'] = var2
            context['group'] = group
            context['today'] = date
            context['address'] = address
            return context
            

class AppointmentCreate(AuthRequiredMixin,SuccessMessageMixin, CreateView):
    logger.debug("start of Appointment create")
    model = MemberAppointment
    success_url = reverse_lazy('Appointment:server_list')
    fields = ['coment',]
    var1 = None
    success_message = "Appointment successfully created and an email reminder has been sent to customer for the same"
       
    def get_context_data(self, **kwargs):
        context = super(AppointmentCreate, self).get_context_data(**kwargs)
        var= customer_request.objects.get(id=self.kwargs['pk'])
        
        var1 = Lead.objects.get(id=var.customer.id)
       
        var2= UserProfile.objects.get(user=var1.member.id)
        user = self.request.user
        group=Group.objects.get(user=user)
        context['req_id'] = self.kwargs['pk']
        context['cust_id'] = var.customer.pk
        context['mem_id'] = var2.id
        context['request_detail'] = var
        context['group'] = group
        return context
        
    def form_valid(self, form, **kwargs):
        user= self.request.user
        detail1 = get_object_or_404(User, pk=user.id)
        detail2 = get_object_or_404(UserProfile, user=detail1)
        cust_detail= customer_request.objects.get(id=self.kwargs['pk'])
        status= Status.objects.get(status="Scheduled")
        print("status:",status)
        cust= Lead.objects.get(pk= cust_detail.customer.id)
        today=datetime.today()
        self.object = form.save(commit=False)
        self.object.request= cust_detail
        self.object.member= detail2
        self.object.customer =cust
        self.object.status =status
        self.object.date_appointment = today.date()
        self.object.date=cust_detail.date
        self.object.from_time=cust_detail.from_time
        self.object.to_time=cust_detail.to_time
        self.object.save()
        cust_detail.status_id = status
        cust_detail.save()
        now = timezone.now()
        variable=Timeline(comment1="have created an ", comment2="Appointment",action_create=now,user=self.request.user)
        variable.save()
#         date=form.cleaned_data['date']
#         from_time=form.cleaned_data['from_time']
#         to_time=form.cleaned_data['to_time']
        ctx={'date': cust_detail.date, 'from_time': cust_detail.from_time, 'to_time': cust_detail.to_time, 'request': cust_detail.description, 'name':detail1.first_name, 'phone':detail2.phone_no, 'shop':detail2.shop_name, 'address':detail2.shop_address}
        data = {}
        l_u=lead_user.objects.get(customer=cust_detail.customer)
        #notify.send(self.request.user, recipient=l_u.user, verb='scheduled an Appointment  ')
        notify.send(self.request.user,recipient=l_u.user,verb="Confirmed your "+str(cust_detail.service_type)+" appointment ",app_name="Appointment",activity="create",object_id=self.object.pk)
        message=str(detail1.first_name)+" "+str(detail1.last_name)+" have scheduled an appointment for your request "+str(cust_detail.service_type.service_type)+" on "+str(cust_detail.date)
        #notifications for ios
        try:        
            deviceiOS = APNSDevice.objects.filter(user=l_u.user.pk)
            print("devices to which notifications is sent: ",deviceiOS)
            message_sent=deviceiOS.send_message(message)
        except Exception as e:
            print("exception------------------------------------------",e.message)
        #notifications for ios end
        #notifications for android
        try: 
            print("user: ",FCMDevice.objects.filter(user=l_u.user.pk))
            device = FCMDevice.objects.filter(user=l_u.user.pk)
            print("devices to which notifications is sent: ",device)
            device.send_message("Appointment",message)
            print("message sent")
        except Exception as e:
            print("exception------------------------------------------",e.message)
         #notifications for android end 
    	send_appt_create_task.delay(str(cust_detail.date),str(cust_detail.from_time),str(cust_detail.to_time),cust_detail.description,detail1.first_name,detail2.phone_no,detail2.shop_name,detail2.shop_address,cust_detail.customer.email,detail1.email,detail2.website)
        return super(AppointmentCreate, self).form_valid(form)    
    
class AppointmentUpdate(AuthRequiredMixin,SuccessMessageMixin, UpdateView):
    logger.debug("start of Appointment update")
    model = MemberAppointment
    template_name = 'Appointment/update_appointment.html'
    form_class = UpdateAppointmentForm
    success_url = reverse_lazy('Appointment:server_list')
    #fields = ['date','from_time', 'to_time','coment']
    success_message = "Appointment successfully updated"
    
    def get_context_data(self, **kwargs):
        context = super(AppointmentUpdate, self).get_context_data(**kwargs)
        var2= MemberAppointment.objects.get(id=self.kwargs['pk'])
        var3=None
        if var2.request:
            var3= customer_request.objects.get(pk = var2.request.id)
        user = self.request.user

Appointment/templates/Appointment/memberappointment_form.html
{% extends "base2.html" %}
{% load static from staticfiles %}
{% load i18n %}

{% block head %}
<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<!--<script src="{% static 'js/validation/appoinment_date.js' %}"></script>-->
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
 
  <link rel="stylesheet" href="{% static 'css/wickedpicker.css' %}">
  
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
 <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
  
  <script type="text/javascript" src="{% static 'js/wickedpicker.js' %}"></script>
  
  <script src="{% static 'js/validation/appointment_form.js' %}"></script>

<script type='text/javascript'>
$(function() {
	
	
	
    $('#id_customer').change(function() {
        // if changed to, for example, the last option, then
        // $(this).find('option:selected').text() == D
        // $(this).val() == 4
        // get whatever value you want into a variable
        var x = $(this).val();
        // and update the hidden input's value
        $('#myhidden').val(x);
    });
    $('#id_member').change(function() {
        // if changed to, for example, the last option, then
        // $(this).find('option:selected').text() == D
        // $(this).val() == 4
        // get whatever value you want into a variable
        var x = $(this).val();
        // and update the hidden input's value
        $('#myhidden1').val(x);
    });
    $('#id_request').change(function() {
        // if changed to, for example, the last option, then
        // $(this).find('option:selected').text() == D
        // $(this).val() == 4
        // get whatever value you want into a variable
        var x = $(this).val();
        // and update the hidden input's value
        $('#myhidden2').val(x);
    });
    $('#id_status').change(function() {
        // if changed to, for example, the last option, then
        // $(this).find('option:selected').text() == D
        // $(this).val() == 4
        // get whatever value you want into a variable
        var x = $(this).val();
        // and update the hidden input's value
        $('#myhidden3').val(x);
    });
});

$(document).ready(function(){
	$("#promo_btn").click(function()
	{
		$("#appointment_form").submit();
	});	
	$("#id_customer").attr("class","form-control");
	$("#id_member").attr("class","form-control");
	$("#id_request").attr("class","form-control");
	$("#id_status").attr("class","form-control");
	$("#id_date").attr("class","form-control");
	$("#id_from_time").attr("class","form-control");
	$("#id_to_time").attr("class","form-control");
	$("#id_coment").attr("class","form-control");
	$(".aaaa").attr("class","form-control");
	$("#pr").prop('disabled', true);
	$("#desc").addClass("form-control");
	$("#desc").prop('disabled',true);
});
</script>

<script>
  $(function() {
	  $( "#id_date" ).datepicker({minDate:0,dateFormat:'dd/mm/yy'});
	//$( "#id_date" ).datepicker({dateFormat:'dd/mm/yy'});
    $('#id_from_time').wickedpicker();
    $('#id_to_time').wickedpicker();

  });
  </script>
 <style>
  .form-control[disabled], .form-control[readonly], fieldset[disabled] .form-control {
    background-color: #f4f6f6;
    opacity: 1;
}
  </style>
  <style>
.seperator{
border-top: 4px solid #F38619;
}
.active_class{
color:#f38619;
}
.btn-primary {
    color: #fff;
    background-color: #337ab7;
    border-color: #2e6da4;
}


</style>

{% endblock %}


{% block content %}
  <!-- Breadcrum -->
  <div class="page-header">
             <h4 class="" style="color: #6B748A;"><span class="glyphicon glyphicon-th-list"></span>
               APPOINTMENT FORM</h4>

        </div>
 <div class="row">   
              
          
          <div class="dropdown pull-right">
 <a href="{%  url 'customer:server_list'   %}">
            <button type="button" class="btn btn-primary " data-dismiss="modal">
               <i class="fa fa-reply" aria-hidden="true">
               </i> Back</button>
           </a>
             <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown">
               <i class="fa fa-floppy-o"></i> Save
                <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                       <li><a id="promo_btn"style="cursor: pointer;"><i class="fa fa-check" aria-hidden="true"></i> Save and Exit</a></li>
                   </ul>
            </div>
       
  </div>

<input type="hidden" id="group" value="{{group.name}}">

<div class="row" >
       <!-- Breadcrum -->
  
	<div class="page"style="margin-bottom:10px;">
         <div class="row">
         <div class="col-md-2"></div>
             <div class="col-md-6 col-xs-6 col-sm-6" >
               <center> <h3><b>Service Request	</b></h3></center>
                {% if request_detail %}
				  
			    <label class="col-md-4 col-xs-6 col-sm-6 control-label" for="model_id">Customer:</label>
			     <div class="col-md-8 col-xs-8 col-sm-8">
			    	 <input type="text" class="form-control" value="{{request_detail.customer.name}}" disabled>
			    	 <span class="help-block"> </span>  
				</div>
			
			<label class="col-md-4 col-xs-6 col-sm-6 control-label" for="model_id">Service Type:</label>
			     
			     <div class="col-md-8 col-xs-8 col-sm-8">
			       <input type="text" class="form-control" value="  {{request_detail.service_type}}" disabled>
			       <span class="help-block"> </span>  
				</div>
                 
                  
					{% if request_detail.promotion %}
					
					 <label class="col-md-4 col-xs-6 col-sm-6 control-label" for="model_id">Promotion:</label>
			     <div class="col-md-8 col-xs-8 col-sm-8">
			      
			     			       <input type="text" class="form-control" value="  {{request_detail.promotion}}" disabled>
			     
                      
			         <span class="help-block"> </span>  
			    </div>
			
	            
             <label class="col-md-4 col-xs-6 col-sm-6 control-label" for="model_id">Discount:</label>
			     
			     <div class="col-md-8 col-xs-8 col-sm-8">
			      
			     	 <input type="text" class="form-control" value=" {{request_detail.promotion.discount}}" disabled>
			      
                 
			         <span class="help-block"> </span>  
			    </div>
			
			<label class="col-md-4 col-xs-6 col-sm-6 control-label" for="model_id">Coupon Code:</label>
			     
			     <div class="col-md-8 col-xs-8 col-sm-8">
			      
			      <input type="text" class="form-control" value="  {{request_detail.promotion.coupon_code}}" disabled>
			      
     
			         <span class="help-block"> </span>  
			    </div>
			
				<label class="col-md-4 col-xs-6 col-sm-6 control-label" for="model_id">From Date:</label>
			     
			     <div class="col-md-8 col-xs-8 col-sm-8">
			     	 <input type="text" class="form-control" value=" {{request_detail.promotion.from_date}}" disabled>
			     
			     
                    
			         <span class="help-block"> </span>  
			    </div>
			
				<label class="col-md-4 col-xs-6 col-sm-6 control-label" for="model_id">To Date:</label>
			     
			     <div class="col-md-8 col-xs-8 col-sm-8">
			    <input type="text" class="form-control" value="  {{request_detail.promotion.to_date}}" disabled>
			    
                   
			         <span class="help-block"> </span>  
			    </div>
			
				
                {% else %} 
                <label class="col-md-4 col-xs-6 col-sm-6 control-label" for="model_id">Date:</label>
			     
			     <div class="col-md-8 col-xs-8 col-sm-8">
			       
			     <input type="text" class="form-control" value="  {{request_detail.date}}" disabled>
			      
                   
			         <span class="help-block"> </span>  
			    </div>
			
			 <label class="col-md-4 col-xs-6 col-sm-6 control-label" for="model_id">From Time:</label>
			     
			     <div class="col-md-8 col-xs-8 col-sm-8">
			     			     <input type="text" class="form-control" value="  {{request_detail.from_time}}" disabled>
			     
			      
                   
			         <span class="help-block"> </span>  
			    </div>
			
			 <label class="col-md-4 col-xs-6 col-sm-6 control-label" for="model_id">To Time:</label>
			     
			     <div class="col-md-8 col-xs-8 col-sm-8">
			       
			      	 <input type="text" class="form-control" value="   {{request_detail.to_time}}" disabled>
			      
                  
			         <span class="help-block"> </span>  
			    
			</div>
				
                
                   
                {% endif %}
                 
                  <label class="col-md-4 col-xs-6 col-sm-6 control-label" for="model_id">Description:</label>
			     
			     <div class="col-md-8 col-xs-8 col-sm-8">
			      <textarea class="form-control" disabled>{{request_detail.description}}</textarea>
			     
			         <span class="help-block"> </span>  
			    </div>
			
               
				<input type="hidden" name="promo_id" id="promotion_id" value="{{promo_detail.pk}}">
				
			
				
				 
				 {% endif %}
                
                               
               
                
	      <div class="col-md-12 col-sm-12 col-xs-12">                   <hr class="separator-line ">
	      
                <center><h3><b>Schedule Appointment</b></h3></center>
			  <form class="form-horizontal" id="appointment_form" method="post" name="form" >{% csrf_token %}
<input id="myhidden1" name="member" type="hidden" value="{{mem_id}}">
<input id="myhidden2" name="request" type="hidden" value="{{req_id}}">
<input id="myhidden3" name="status" type="hidden" value="5">
<input id="myhidden" name="customer" type="hidden" value="{{cust_id}}">
	         <input type='hidden' id='id_hidden' value=''>
    	      
    	      
			<!-- <div class="form-group">
			    <label class="col-md-5 col-xs-5 col-sm-6 control-label" for="model_id">Date*:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7">
                       {{form.date}} <div id="error7" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
                <div class="form-group">
			    <label class="col-md-5 col-xs-5 col-sm-6 control-label" for="model_id">From Time*:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7">
                       {{form.from_time}} <div id="error8" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
				
			   <div class="form-group">
			    <label class="col-md-5 col-xs-5 col-sm-6 control-label" for="model_id">To Time*:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7">
                       {{form.to_time}} <div id="error9" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div> -->
				
		    <div class="form-group">
			    <label class="col-md-5 col-xs-6 col-sm-6 control-label" for="model_id">Comment*:</label>  
			     <div class="col-md-7 col-xs-7 col-sm-7">
                       {{form.coment}}<div id="err7" style="color:red"></div>

			         <span class="help-block"> </span>  
			    </div>
			</div>
		   
				
				 

		
      
      </form>
      </div>
      </div>

	</div>
</div></div>
    
    
{% endblock %}