Autoxtion_B2C/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django import views
from Registration import views
import promotion.urls
import customer.urls
import Feedback.urls
import Appointment.urls
import api.urls
from django.conf import settings
import notifications.urls 

#handler404 = 'Registration.views.custom_404'

#if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
 #   urlpatterns += patterns('',
  #          url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
   # )


urlpatterns = [
    #url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^admin/', admin.site.urls),
    url(r'^registration/', include('Registration.urls')),
    url(r'^email/', include('password_reset.urls')),
    url(r'^CRM/',include('CRM.urls',namespace='CRM')),
    url(r'^promotion/', include(promotion.urls, namespace='promotion')),
    url(r'^customer/', include(customer.urls, namespace='customer')),
    url(r'^feedback/', include(Feedback.urls, namespace='Feedback')),
    url(r'^appointment/', include(Appointment.urls, namespace='Appointment')),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^api/', include(api.urls, namespace='api')),
    url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

CRM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
urlpatterns = [

    url(r'^$',views.index,name="index"),
    url(r'addlead/$',views.addlead,name="addlead"),
    #url(r'addlead/$',views.addlead.as_view(),name="addlead"),
    url(r'^edit/(?P<lead_id>[0-9]+)/$', views.edit_lead, name='edit_lead'),
    url(r'^change_status/(?P<lead_id>[0-9]+)/$', views.change_status, name='change_status'),
    url(r'^get_models/$', views.get_models),
    url(r'^get_mod/$', views.get_mod),
    url(r'^get_make_year/$', views.get_make_year),
    #url(r'^qualify_lead/$', views.qualify_lead,name="qualify_lead"),
    url(r'^crmcust/$', views.customer_index, name='customer_index'),
    url(r'^deleteVehicle/$',views.deleteVehicle,name="deleteVehicle"),
    url(r'^index2/(?P<d>[0-9]+)/$', views.index2,name="index2"),
    url(r'^customer_index2/(?P<d>[0-9]+)/$', views.customer_index2,name="cindex2"),
    url(r'^existing_cust/$', views.existing_cust,name="existing_cust"),
    url(r'^addVehicle/$', views.addVehicle,name="addVehicle"),
    url(r'^editVehicle/$', views.editVehicle,name="editVehicle"),
    url(r'^deleteVehicleCust/$',views.deleteVehicleCust,name="deleteVehicleCust"),
    url(r'^excelsheetimport/$',views.excelsheet,name="excelsheet"),
    url(r'^view_history/(?P<lead_id>[0-9]+)/$', views.view_history, name='view_history'),
    url(r'^customerRegistration/$', views.customer_registration, name='customer_registration'),  
    url(r'^customerdel/$', views.customer_delete,name="customerdel"), 
    url(r'^get_customerlist/(?P<user_id>[0-9]+)/(?P<from_dt>\d{4}-\d{2}-\d{2})/(?P<to_dt>\d{4}-\d{2}-\d{2})/$',  views.get_customer.as_view()),
    url(r'^get_leadlist/(?P<user_id>[0-9]+)/(?P<from_dt>\d{4}-\d{2}-\d{2})/(?P<to_dt>\d{4}-\d{2}-\d{2})/$',  views.get_leadlist.as_view()),
    url(r'^add/(?P<mem_detail>[0-9]+)$',views.add),
    url(r'^downloadExcelTemplate',views.downloadDemoTemplate,name="downloadexceltemplate"),
    url(r'^generate_credentials/$', views.generateCredentials,name="generateCredentials"),
    url(r'addCompany/$',views.addCompany,name="addCompany"),
    url(r'UpdateCompany/(?P<company_id>[0-9]+)/$',views.UpdateCompany,name="UpdateCompany"),
    url(r'^driver_delete_ajax/(?P<vehicle_id>\d+)$',views.driver_delete_ajax, name='driver_delete_ajax'),
    url(r'^edit_drivers/$',views.edit_drivers, name='edit_drivers'),
    url(r'^company_list/$', views.company_index, name='company_index'),

]

Feedback/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
 
 
urlpatterns = [
 
#url(r'^$', views.FeedbackList, name='server_list'),
#url(r'^new$', views.FeedbackCreate.as_view(), name='server_new'),
url(r'^get_lead/',views.get_lead),
url(r'^new/$',views.FeedbackCreate, name='server_new'),
#url(r'^viewfeed/(?P<feed_id>[0-9]+)/$', views.viewfeedback, name='viewfeedback'),
url(r'^get_feeds/',views.get_feeds,name="get_feeds"),
url(r'^view_feed/',views.view_feed,name="view_feed"),
url(r'^new$', views.FeedbackCreate, name='server_new'),

]

Registration/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views
from django.core.urlresolvers import reverse_lazy,reverse

app_name = 'Registration'

urlpatterns = [
    url(r'^login/$', views.login,name='login'),

    url(r'^member_login/$', views.member_login,name='member_login'),
    url(r'^customer_login/$', views.customer_login,name='customer_login'),

    url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page':'/registration/login'}),
    url(r'^register/$', views.register, name='register'),
    url(r'^updatedetails/(?P<user_id>[0-9]+)', views.updatedetails, name='updatedetails'),
    url(r'^success/$', views.success, name='success'),
    url(r'^EBC/(?P<user_id>[0-9]+)', views.businesscard, name='businesscard'),
    url(r'^EBC_cust/(?P<user_id>[0-9]+)', views.businesscard_cust, name='businesscard_cust'),
    url(r'^FAQ/$', views.faq,name='faq'),
    url(r'^enroll/$', views.enroll,name='enroll'),
    url(r'^usermanual/$',views.pdfopen,name='pdfopen'),
    url(r'^payment/$',views.payment),
    url(r'^newpayment/$',views.newpayment),
    url(r'^unsubscribe/$',views.unsubscribe),
    url(r'^subscribe/$',views.subscribe,name="subscribe"),
    url(r'^resubscribe/$',views.resubscribe),
    url(r'^demologin/$',views.demologin,name='demologin'),  
    url(r'^get_vcard/$',views.getVcard,name='sendebc'),
    url(r'^get_vcard1/$',views.getVcard1,name='sendcard'),
    url(r'^user_image/(?P<user_id>[0-9]+)', views.user_image, name='user_image'),
    url(r'^user_header_image/$',views.user_header_image, name='user_header_image'),
    url(r'^Contct_us/$', views.contact,name='contact'),
    url(r'^Video_tutorial/$', views.Video_tutorial,name='Video_tutorial'),
    url(r'^member_agree/$', views.member_agree,name='member_agree'),
    url(r'^member_agree2/$', views.member_agree2,name='member_agree2'),
    url(r'^unlink_member/$', views.unlink_member,name='unlink_member'),
]
    

customer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
              
   url(r'^$', views.RequestList.as_view(), name='server_list'),
   #url(r'^$', views.CustomerRequestList, name='server_list'),
   url(r'^new_req/$', views.RequestnewCreate.as_view(), name='server_new_req'),
   url(r'^new/(?P<pk>\d+)$', views.RequestCreate.as_view(), name='server_new'),
   url(r'^edit/(?P<pk>\d+)$', views.RequestUpdate.as_view(), name='server_edit'),
   url(r'^delete/(?P<pk>\d+)$', views.RequestDelete.as_view(), name='server_delete'),
   url(r'^get_lead/',views.get_lead),
   #url(r'^get_promo/(?P<requestid>\d+)$',views.get_promo.as_view()),
   url(r'^memberedit/(?P<pk>\d+)$',views.MemberEditRequest.as_view(), name='member_edit_request'),
   url(r'^confirm/(?P<customer_request_id>[0-9]+)/$',views.ConfirmRequest, name='confirm_request'),
   url(r'^accept/(?P<customer_request_id>[0-9]+)/$',views.AcceptRequest, name='accept_request'),


   url(r'^customer_history/$', views.customer_history.as_view(), name='customer_history'),
   url(r'^EmergencyRequestList/$', views.EmergencyRequestList.as_view(), name='EmergencyRequestList'),
   url(r'^Add_emergency_req/$', views.Add_emergency_req.as_view(), name='Add_emergency_req'),
   url(r'^edit_emergency_req/(?P<pk>\d+)$', views.edit_emergency_req.as_view(), name='edit_emergency_req'),
   url(r'^membereditemergency/(?P<pk>\d+)$',views.MemberEditRequestEmergency.as_view(), name='member_edit_emergency'),
   url(r'^delete_emergency_req/(?P<pk>\d+)$', views.delete_emergency_req.as_view(), name='delete_emergency_req'),
   url(r'^emer_confirm/(?P<customer_request_id>[0-9]+)/$',views.Emer_ConfirmRequest, name='emer_confirm_request'),
]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])

promotion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from rest_framework import routers

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
#app_name = 'promotion
from rest_framework.urlpatterns import format_suffix_patterns
#router = routers.SimpleRouter()

#router.register(r'get_promotion', views.get_promotion.as_view())
#router.register(r'get_services', views.NewPromoList)


urlpatterns = [
              
   url(r'^$', views.PromotionList.as_view(), name='server_list'),
   url(r'^all$', views.PromotionListall.as_view(), name='server_list_all'),
   url(r'^list$', views.Promo_List_Mem.as_view(), name='server_list_mem'),
   #url(r'^new$', views.PromotionCreate.as_view(), name='server_new'),
   url(r'^new_all$', views.PromotionCreate.as_view(), name='server_new'),
   #url(r'^detail/(?P<pk>\d+)$', views.ServerDetail.as_view(), name='server_detail'),
   url(r'^edit/(?P<pk>\d+)$', views.PromotionUpdate.as_view(), name='server_edit'),
   url(r'^delete/(?P<pk>\d+)$', views.PromotionDelete.as_view(), name='server_delete'),
   url(r'^test/$',views.getmodel, name='test'),
   url(r'^get_promotion/(?P<val>.+)/$',  views.get_promotion.as_view()),
   url(r'^promotion_history/$', views.promotion_history, name='promotion_history'),
   url(r'^promotion_reopen/(?P<pk>\d+)$', views.promotion_reopen, name='promotion_reopen'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])

Autoxtion_B2C/templates/base1.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
<head>
  <title>Auto Xtion</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="icon" type="image/png" href="{% static 'images/ico2.png' %}">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height:auto;}
    
   
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: auto) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
   
  </style>
  {% block head %}

{%endblock%}
</head>
<body>

   <nav class="upper-nav" style="background-color:#fff;
    box-shadow: 1px 2px 5px #888888;">
  <div class="container-fluid">
    <div class=" row ">
    
      <div class="col-md-4"></div>
      
      <div class="col-md-3"><center> <a href="/registration/login/"><img alt="" src="/static/images/logo_new.png"></a></center></div>
      
      
    </div>
    
  </div>
  </nav>
   
{%block content%}
          {% endblock%}
   
<!-- start of footer-->

 <footer style="">
	<div class="foot"style="background-color:#39484A; color: #CCCCCC; padding-top:20px;">
	<div class="container">
			<div class="row" >
			 <div class=" col-md-2 col-xs-4 logo" "><img alt="logo" src="/static/images/logo_new.png">		
					
		  </div>
		   <div class=" col-md-1 col-xs-3" style="padding-top:85px;" >
	<center><p id="footer_crm"><span class="glyphicon  glyphicon-menu-right" style="padding-left:8px;"></span><a href="/registration/login/"><font color="#f38619"> Home</font> </a></p>
      <center><p id="footer_crm"><span class="glyphicon  glyphicon-menu-right"></span><a href="{% url 'Registration:faq' %}" target="_blank"><font color="#f38619">  FAQ </font> </a></p>
     </center>
     <center><p id="footer_crm"><span class="glyphicon  glyphicon-menu-right" style="padding-left:7px;"></span><a href="{% url 'Registration:pdfopen' %}" target="_blank" ><font color="#f38619">  HELP </font> </a></p></center>
     </div>
			  
					 
					 
						<div class=" col-md-4 col-xs-7" style="float:right">
							<h3>CONTACT US</h3> 
							<hr class="separator-line">
							<p>P.O. Box 2557</p>
							<p> North Parramatta,1750</p>
                          				<p>Email: info@autoxtion.com.au</p>
							
					   </div>
		
		</div></div>
  </div>
 </footer>
 <div class="footer-small" style="background-color:#2c383a;color:#fff;padding:5px;">
      <center><font>&copy;Auto Xtion 2016</font></center>
   </div>
<!-- end of footer -->
</body>
</html>

Autoxtion_B2C/templates/base2.html
{% load static from staticfiles %}
 {% load notifications_tags %}

<html><head><meta http-equiv="Content-Type" content="text/html; charset=windows-1252">


<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<link href="{% static 'css/new_style.css' %}" rel="stylesheet">
<script src="{% static 'js/notify.js' %}" type="text/javascript"></script>
{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
<script type="text/javascript" src="{% static 'js/notification.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/role.js' %}" ></script>
<style>
footer{
position: initial;
  bottom: 0;
  width: 100%;
  / Set the fixed height of the footer here /
  height: 60px;
  background-color: #f5f5f5;
}
.affix-row{
 margin-top:-20px
}
.navbar {
    position: fixed !important;
    min-height: 50px;
    margin-bottom: 20px;
    border: 1px solid transparent;
    z-index: 999 !important;
    width: 100% !important;
}
</style>
<script>
$(document).ready(function(){

 $.ajax({
		url:'/registration/user_header_image/',
	    type: 'GET',
	    
	}).done(function(data){
		console.log(data);
		//var image=$("#user_img").attr("src","/static/"+data);
		$('#user_i').attr('src',"/media/"+data);
	  
	    
	});
});
</script></head>
{%block styleBlock%}

{%endblock%}
{% block head %}

{%endblock%}
<body>


<div class="example2">
    <nav class="navbar navbar-default" style="background-color:#f38619;">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar2"> <span class="sr-only">Toggle navigation</span>
 <span class="icon-bar"></span>

                    <span class="icon-bar"></span> <span class="icon-bar"></span>

                </button> <a class="pull-left cusImg" href=""><img src="{% static 'images/AutoXtion-logo.png' %}" class=""></a>

                <span class="name pull-left" style="color: #ffffff;">Auto Xtion Communication Platform</span>
            </div>
            <div id="navbar2" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    
                     <li id="emergency_count_link"><a href="{% url 'customer:EmergencyRequestList' %}" style="color: #ffffff;opacity:0.9;" >
          		        <span style="color:red;"class="glyphicon glyphicon-bell custom"></span>Emergency Service
		          		
 					<span class="badge badge-notify" id="emergency_count" >0</span>
                          </a>
                    </li>
                    <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
             <div class="header-photo-wrap">
			<img class="img-circle ng-scope" id="user_i"></div>
             <span class="caret"></span>
              </a>

                        <ul class="dropdown-menu" role="menu"><a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              </a>

                            <li id="profile"><a href="{% url 'Registration:updatedetails' user.id %}" class="" style="color: #6B748A;"><span class="glyphicon glyphicon-user"></span> Profile</a>

                            </li>

                             <li id="history"><a href="{% url 'customer:customer_history' %}" class="" style="color: #6B748A;"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;History</a>

                            </li>

                            <li id="enroll"><a href="{% url 'Registration:enroll' %}" class="" style="color: #6B748A;"><span class="glyphicon glyphicon-usd"></span> Enrolment</a>

                            </li>
                            <li id="ebc"><a href="{% url 'Registration:businesscard' user.id %}" class="" style="color: #6B748A;"><span class="fa fa-credit-card" aria-hidden="true"></span> Business Card</a>

                            </li>
                             <li id="ebc_cust"><a href="{% url 'Registration:businesscard_cust' user.id %}" class="" style="color: #6B748A;"><span class="fa fa-credit-card" aria-hidden="true"></span> Business Card</a>

                            </li>
                            <li class="divider"></li>
                            <li  id="logout"><a href="/registration/logout/"><span class="glyphicon glyphicon-log-out"></span>
                            Log Out </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
        <!--/.container-fluid -->
    </nav>
</div>
<div class="row affix-row" >
    <div class="col-sm-3 col-md-2 affix-sidebar">
        <div class="sidebar-nav" style="height:100%">
            <div class="navbar navbar-default" role="navigation" style="height:100%;background-color:#ffffff;">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse"> <span class="sr-only"></span>
 <span class="icon-bar"></span>

                        <span class="icon-bar"></span> <span class="icon-bar"></span>

                    </button> <span class="visible-xs navbar-brand" style="color: #6B748A;"></span>

                </div>
                <div class="navbar-collapse collapse sidebar-navbar-collapse">
                    <ul class="nav navbar-nav" id="sidenav01">
                        <li> <a href="#" data-toggle="collapse" data-target="#toggleDemo0" data-parent="#sidenav01" class="collapsed" style=" color: #39484A;margin-top: 60px;">
          <h3 class="" style="color: #6B748A;">
         Welcome
          <br class="">
          <small class="" style=" color: #3498db;">  {{cust}}  {{user.first_name}} {{user.last_name}}</small>
          </h3>
          </a>

                        </li>
                        <li id="dashboard_cust"> <a  href="/registration/success/" data-toggle="collapse" data-target="#toggleDemo" data-parent="#sidenav01" class="collapsed"
                          {% if "/success/" in request.path  %} style="background-color:#f38619; color:#fff;" {% endif %}>
                         <span class="glyphicon glyphicon-dashboard"></span> Dashboard      </a> </li>
                        
			 <li id="vehicle"> <a  {% if "CRM" in request.path  %} style=" background-color:#f38619; color: #fff;" {% endif %} href="{% url 'CRM:editVehicle' %}" data-toggle="collapse" data-target="#toggleDemo" data-parent="#sidenav01" class="collapsed">
                         <span class="glyphicon glyphicon-dashboard"></span> Vehicle    </a> </li>
                       
			 <li  id="crm">
			 <a  data-toggle="collapse" data-target="#toggleDemo2" data-parent="#sidenav01" class="collapsed" {% if "CRM" in request.path %} style=" background-color:#f38619; color: #ffffff;" {% endif %} {% if "crmcust" in request.path %} style=" background-color:#f38619; color: #ffffff;" {% endif %} >
          <span class="glyphicon glyphicon-inbox"></span> CRM<span class="caret pull-right" style="float: none !important;margin-left: 120px;margin-top:0px"></span>
          </a>

                            <div class="collapse" id="toggleDemo2" style="height: 0px;">
                                <ul class="nav nav-list">
                                    <li><a 	href="{% url 'CRM:index' %}" class=""><i class="fa fa-user" aria-hidden="true"></i> Lead Generation</a>

                                    </li>
                                    <li><a href="{% url 'CRM:customer_index' %}" class="" ><i class="fa fa-users" aria-hidden="true"></i> Customer</a>

                                    </li>
 					 <li><a href="{% url 'CRM:company_index' %}" class="" ><i class="fa fa-briefcase" aria-hidden="true"></i> Company</a>

                                    </li>

                                    <li><a href="{% url 'CRM:excelsheet' %}" class="" ><i class="fa fa-upload" aria-hidden="true"></i> Excel Upload</a>

                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li id="service_request"><a href="{% url 'customer:server_list'  %}" class="" {% if "customer" in request.path  %} style=" background-color:#f38619; color: #ffffff;" {% endif %} ><i class="fa fa-star" aria-hidden="true"></i> Service Request</a>

                        </li>
                        <li id="promotion_cust"><a href="{% url 'promotion:server_list'  %}" class="" {% if "promotion" in request.path %} style=" background-color:#f38619; color: #ffffff;" {% endif %}><i class="fa fa-bullhorn" aria-hidden="true"></i> Promotions </a>

                        </li>
                        <li id="promotion_mem"><a href="{% url 'promotion:server_list_mem'  %}" class="" {% if "promotion" in request.path %} style=" background-color:#f38619; color: #ffffff;" {% endif %}><i class="fa fa-bullhorn" aria-hidden="true"></i> Promotions </a>

                        </li>
                        <li id="appointment"><a href="{% url 'Appointment:server_list'  %}" class="" {% if "appointment" in request.path  %} style=" background-color:#f38619; color: #ffffff;" {% endif %}><i class="fa fa-calendar" aria-hidden="true"></i> Appointments</a>

                        </li>
                          <li id="id_notification" class="normal_count_link"><a href="{% url 'notifications:all' %}" class="" {% if "notifications" in request.path %} style=" background-color:#f38619; color: #ffffff;" {% endif %}><i class="fa fa-bell" aria-hidden="true"></i> Notification
                         
                          <span class="badge" style="margin-left: 60px; float: none !important;background-color: #00bca4" id="normal_count">0</span>
                         
                          </a>

                        </li>                     <li id="feedback"><a href="{% url 'Feedback:server_new'  %}" class="" {% if "feedback" in request.path  %} style=" background-color:#f38619; color: #ffffff;" {% endif %}><i class="fa fa-envelope" aria-hidden="true"></i> Feedback </a>

                        </li>
                        <li id="id_video"><a href="{% url 'Registration:Video_tutorial'  %}" class="" {% if "Video_tutorial" in request.path  %} style=" background-color:#f38619; color: #ffffff;" {% endif %}><i class="fa fa-video-camera" aria-hidden="true"></i> Video Tutorials </a>

                        </li>

                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <div class="col-sm-9 col-md-10 affix-content" style="border-left:1px Solid #E2E7F4;">
       <!--  <div class="page-header">
            	<h4 class="" style="color: #6B748A;"><span class="glyphicon glyphicon-th-list"></span>
                  LEAD GENERATION</h4>

        </div> -->
      <div class="page-display" style="min-height: calc(87vh - 40px);margin-bottom:114px;margin-top: 86px;">
         {%block content%}
         {% endblock %}
        </div>
         <div class="footer">

           <a href="#" style="float:left;color: #6B748A;
text-decoration: none"> AUTO XTION  {% now "Y" %}</a>

            <a href="https://www.autoxtion.com.au/" target="_blank" style="color: #6B748A;
text-decoration: none;margin-right: 20px"><i class="fa fa-info-circle" aria-hidden="true"></i> About Us</a>
            <a href="{% url 'Registration:faq' %}" style="color: #6B748A;
text-decoration: none;margin-right: 20px" target="_blank"><i class="fa fa-question-circle" aria-hidden="true"></i> FAQ</a>
        	<a href="{% static 'pdf/Auto Xtion Privacy Policy Ver A.pdf' %}" style="color: #6B748A;
text-decoration: none;margin-right: 20px" target="_blank"><i class="fa fa-asterisk" aria-hidden="true"></i> Terms &amp; Condtions</a>
                       <a href="{% url 'Registration:contact' %}" style="color: #6B748A;
text-decoration: none;margin-right: 20px" target="_blank"><i class="fa fa-map-marker" aria-hidden="true"></i> Contact</a>

           <ul class="social-network social-circle" style="float:right;margin-top:-5px;">

                        <li><a style="background-color: #3B5998;" href="https://www.facebook.com/autoxtion/?fref=ts" class="icoFacebook" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a></li>
                        <li><a style="background-color: #33ccff;" href="https://twitter.com/auto_xtion?lang=en" class="icoTwitter" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a></li>

                        <li><a style="background-color: #007bb7;" href="https://au.linkedin.com/in/ravi-naik-513054117" class="icoLinkedin" title="Linkedin" target="_blank"><i class="fa fa-linkedin"></i></a></li>
            </ul>
      	</div>
          </div>
</div>


</body></html>