Autoxtion_B2C/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django import views
from Registration import views
import promotion.urls
import customer.urls
import Feedback.urls
import Appointment.urls
import api.urls
from django.conf import settings
import notifications.urls 

#handler404 = 'Registration.views.custom_404'

#if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
 #   urlpatterns += patterns('',
  #          url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
   # )


urlpatterns = [
    #url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^admin/', admin.site.urls),
    url(r'^registration/', include('Registration.urls')),
    url(r'^email/', include('password_reset.urls')),
    url(r'^CRM/',include('CRM.urls',namespace='CRM')),
    url(r'^promotion/', include(promotion.urls, namespace='promotion')),
    url(r'^customer/', include(customer.urls, namespace='customer')),
    url(r'^feedback/', include(Feedback.urls, namespace='Feedback')),
    url(r'^appointment/', include(Appointment.urls, namespace='Appointment')),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^api/', include(api.urls, namespace='api')),
    url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

CRM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
urlpatterns = [

    url(r'^$',views.index,name="index"),
    url(r'addlead/$',views.addlead,name="addlead"),
    #url(r'addlead/$',views.addlead.as_view(),name="addlead"),
    url(r'^edit/(?P<lead_id>[0-9]+)/$', views.edit_lead, name='edit_lead'),
    url(r'^change_status/(?P<lead_id>[0-9]+)/$', views.change_status, name='change_status'),
    url(r'^get_models/$', views.get_models),
    url(r'^get_mod/$', views.get_mod),
    url(r'^get_make_year/$', views.get_make_year),
    #url(r'^qualify_lead/$', views.qualify_lead,name="qualify_lead"),
    url(r'^crmcust/$', views.customer_index, name='customer_index'),
    url(r'^deleteVehicle/$',views.deleteVehicle,name="deleteVehicle"),
    url(r'^index2/(?P<d>[0-9]+)/$', views.index2,name="index2"),
    url(r'^customer_index2/(?P<d>[0-9]+)/$', views.customer_index2,name="cindex2"),
    url(r'^existing_cust/$', views.existing_cust,name="existing_cust"),
    url(r'^addVehicle/$', views.addVehicle,name="addVehicle"),
    url(r'^editVehicle/$', views.editVehicle,name="editVehicle"),
    url(r'^deleteVehicleCust/$',views.deleteVehicleCust,name="deleteVehicleCust"),
    url(r'^excelsheetimport/$',views.excelsheet,name="excelsheet"),
    url(r'^view_history/(?P<lead_id>[0-9]+)/$', views.view_history, name='view_history'),
    url(r'^customerRegistration/$', views.customer_registration, name='customer_registration'),  
    url(r'^customerdel/$', views.customer_delete,name="customerdel"), 
    url(r'^get_customerlist/(?P<user_id>[0-9]+)/(?P<from_dt>\d{4}-\d{2}-\d{2})/(?P<to_dt>\d{4}-\d{2}-\d{2})/$',  views.get_customer.as_view()),
    url(r'^get_leadlist/(?P<user_id>[0-9]+)/(?P<from_dt>\d{4}-\d{2}-\d{2})/(?P<to_dt>\d{4}-\d{2}-\d{2})/$',  views.get_leadlist.as_view()),
    url(r'^add/(?P<mem_detail>[0-9]+)$',views.add),
    url(r'^downloadExcelTemplate',views.downloadDemoTemplate,name="downloadexceltemplate"),
    url(r'^generate_credentials/$', views.generateCredentials,name="generateCredentials"),
    url(r'addCompany/$',views.addCompany,name="addCompany"),
    url(r'UpdateCompany/(?P<company_id>[0-9]+)/$',views.UpdateCompany,name="UpdateCompany"),
    url(r'^driver_delete_ajax/(?P<vehicle_id>\d+)$',views.driver_delete_ajax, name='driver_delete_ajax'),
    url(r'^edit_drivers/$',views.edit_drivers, name='edit_drivers'),
    url(r'^company_list/$', views.company_index, name='company_index'),

]

promotion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from rest_framework import routers

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
#app_name = 'promotion
from rest_framework.urlpatterns import format_suffix_patterns
#router = routers.SimpleRouter()

#router.register(r'get_promotion', views.get_promotion.as_view())
#router.register(r'get_services', views.NewPromoList)


urlpatterns = [
              
   url(r'^$', views.PromotionList.as_view(), name='server_list'),
   url(r'^all$', views.PromotionListall.as_view(), name='server_list_all'),
   url(r'^list$', views.Promo_List_Mem.as_view(), name='server_list_mem'),
   #url(r'^new$', views.PromotionCreate.as_view(), name='server_new'),
   url(r'^new_all$', views.PromotionCreate.as_view(), name='server_new'),
   #url(r'^detail/(?P<pk>\d+)$', views.ServerDetail.as_view(), name='server_detail'),
   url(r'^edit/(?P<pk>\d+)$', views.PromotionUpdate.as_view(), name='server_edit'),
   url(r'^delete/(?P<pk>\d+)$', views.PromotionDelete.as_view(), name='server_delete'),
   url(r'^test/$',views.getmodel, name='test'),
   url(r'^get_promotion/(?P<val>.+)/$',  views.get_promotion.as_view()),
   url(r'^promotion_history/$', views.promotion_history, name='promotion_history'),
   url(r'^promotion_reopen/(?P<pk>\d+)$', views.promotion_reopen, name='promotion_reopen'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])

promotion/models.py
from __future__ import unicode_literals

from django.db import models
from CRM.models import *
from django.contrib.auth.models import User
from Registration.models import UserProfile

from django.db import models
from .models import *

# Create your models here.
    
class Service(models.Model):
    service_type= models.CharField(max_length=244)
    
    def __str__(self):
        return self.service_type
    
    class Meta:
        db_table="promotion_service"

       
class Promotions(models.Model):
    company=models.ForeignKey(Company,on_delete=models.CASCADE)
    model_id=models.ForeignKey(Company_Model,on_delete=models.CASCADE)
    make_year=models.ForeignKey(Make_Year1,on_delete=models.CASCADE)
    member=models.ForeignKey(User,on_delete=models.CASCADE)
    Service_id= models.ForeignKey(Service,on_delete=models.CASCADE)
    discount= models.IntegerField(blank=True, null=True)
    description= models.CharField(max_length=244, blank=True, null=True)
    from_date= models.DateField()
    to_date= models.DateField()
    coupon_code=models.CharField(max_length=12,blank=True, null=True)
    price= models.CharField(max_length=11, blank=True, null=True)
    image = models.ImageField(blank=True, null=True)
    date_promo = models.DateField(blank=True, null=True)
    date_update = models.DateField(blank=True, null=True)
    display_to = models.CharField(max_length=20,blank=True, null=True)
    total_amount=models.IntegerField(blank=True, null=True)    
    def __str__(self):
        return self.description
    
    class Meta:
        db_table="promotion_promotions"

promotion/views.py
from django.shortcuts import render, render_to_response
#from promotion.forms import PromotionForm, ModelForm, CompanyForm
from django.template import RequestContext
from django.views.generic.edit import CreateView
from promotion.models import *
from .forms import *
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from CRM.models import *
from django.http import JsonResponse
from django.forms.models import model_to_dict
import logging
from django.core.exceptions import ObjectDoesNotExist
from datetime import date
from django.db.models.query import QuerySet
from django.contrib.gis.serializers.geojson import Serializer
from django.contrib.auth.views import redirect_to_login
from django.views.generic.detail import DetailView
logger = logging.getLogger('promotion')
logger.addHandler(logging.NullHandler())
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User, Group
from CRM.models import *
from datetime import datetime,time
from rest_framework import viewsets
from .serializers import *
from rest_framework import generics
from django.conf import settings
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import AccessMixin
from django.template.response import TemplateResponse
from promotion.mixin import *
from notifications.signals import notify
from customer.models import *
from django.shortcuts import render,get_object_or_404, render_to_response,redirect
from Timeline.models import *
from django.utils import timezone
from promotion.filters import *
from fcm_django.models import FCMDevice
from push_notifications.models import  APNSDevice
from django.db.models import Q
# Create your views here.

class PromotionList(AuthRequiredMixin, ListView):
    model= Promotions
    template_name = 'promotion/promotions_list.html'
    success_url = reverse_lazy('promotion:server_list')
    
    def get_context_data(self, **kwargs):
        #print("in get context")
        context = super(PromotionList, self).get_context_data(**kwargs)
        response = TemplateResponse(self.request, self.template_name)
        user = self.request.user
        group=Group.objects.get(user=user)
	address=None
        if group.name=="Company":
            obj=[]
            #print("in company")
            company_obj=CustCompany.objects.get(email=user.email)
            #print("Company obj",company_obj)
            driver_list=Company_Driver.objects.filter(company=company_obj)
            for driver in driver_list:
                lead_obj=Lead.objects.get(pk=driver.driver.pk)
                #print(lead_obj)
                veh=Lead_Vehicle.objects.filter(lead=lead_obj)
                today=datetime.today()
                msg=None
                if veh:
                    #print("Vehicle object",veh)
                    for vehicle in veh:
                        print("vehicle details",vehicle.company.pk," ",vehicle.model.pk," ",vehicle.makeyear.pk," ",today.date())
                        var2=Promotions.objects.filter(member=company_obj.member,
                                                       company=vehicle.company,
                                                       model_id=vehicle.model,
                                                       make_year=vehicle.makeyear,
                                                       to_date__gte = today.date(),
                                                       display_to="Customer")
                        print("QQQQQQQ1",var2)
                        for v in var2:
                            obj.append(model_to_dict(v))
                        promo_list2=Promotions.objects.filter(member=company_obj.member,
                                                              company=vehicle.company,
                                                              model_id=vehicle.model,
                                                              make_year=vehicle.makeyear,
                                                              to_date__gte = today.date(),
                                                              display_to="Lead")
                        print("QQQQQQQ2",promo_list2)
                        for v in promo_list2:
                            obj.append(model_to_dict(v))
                        try:
                            allpromo=Promotions.objects.filter(member=company_obj.member,
                                                               company=vehicle.company,
                                                               model_id=vehicle.model,
                                                               make_year=vehicle.makeyear,
                                                               to_date__gte = today.date(),
                                                               display_to="All")
                            print("QQQQQQQ3",allpromo)
                            for f in allpromo:
                                obj.append(model_to_dict(f))
                        except Exception as e:
                            pass
                            print("no promotion for ALL")
            print("final obj list",obj)
            com=Company.objects.get(company_name='All')
            var3=Promotions.objects.filter(company=com,member=company_obj.member,to_date__gte = today.date())

            for pv in var3:
                obj.append(model_to_dict(pv))

            count=None
            if len(obj)>7:
                count=1
            print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",obj)
            context['object_list'] = obj
            context['group'] = group

            context['count'] = count
            return context

        else:
            lead_u=lead_user.objects.get(user=user)

            lead_obj=Lead.objects.get(pk=lead_u.customer.pk)

            group=Group.objects.get(user=user)
            groupname=group.name
            #var3=lead_user.objects.get(user=user)
            #var1 = Lead.objects.get(pk=var3.customer.pk)
            #address= UserProfile.objects.get(user=lead_obj.member)
            #print("-------------address",address.shop_name)
            obj=[]
            veh=Lead_Vehicle.objects.filter(lead=lead_obj)
            today=datetime.today()
            msg=None
            print(groupname)
            if groupname=="Customer":
                if veh:
                    for vehicle in veh:
                        if groupname != "All":
                            #var2=Promotions.objects.filter(member=lead_obj.member,company=vehicle.company,model_id=vehicle.model,make_year=vehicle.makeyear, to_date__gte = today.date())
                            var2=Promotions.objects.filter(member=lead_obj.member,company=vehicle.company,model_id=vehicle.model,make_year=vehicle.makeyear, to_date__gte = today.date(),display_to="Customer")
                            print("QQQQQQQ1",var2)
                            for v in var2:
                                obj.append(model_to_dict(v))
                        #if groupname == "All":
                        try:
                            allpromo=Promotions.objects.filter(member=lead_obj.member,company=vehicle.company,model_id=vehicle.model,make_year=vehicle.makeyear, to_date__gte = today.date(),display_to="All")
                            print("QQQQQQQ2",allpromo)
                            for f in allpromo:
                                obj.append(model_to_dict(f))
                        except Exception as e:
                            pass
                            print("no promotion for ALL")
                com=Company.objects.get(company_name='All')

                #modd=Company_Model.objects.get(model_name='All')
                #mk=Make_Year1.objects.get(make_year='All')
                var3=Promotions.objects.filter(company=com,member=lead_obj.member,to_date__gte = today.date())

                for pv in var3:
                    obj.append(model_to_dict(pv))
                #print(len(obj))
                count=None
                if len(obj)>7:
                    count=1
                print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",obj)
                context['object_list'] = obj
                context['group'] = group
                #context['address'] = address
                context['count'] = count
                return context
            if groupname=="Lead":
                if veh:

                    for vehicle in veh:
                        if groupname != "All":
                            #var2=Promotions.objects.filter(member=lead_obj.member,company=vehicle.company,model_id=vehicle.model,make_year=vehicle.makeyear, to_date__gte = today.date())
                            var2=Promotions.objects.filter(member=lead_obj.member,company=vehicle.company,model_id=vehicle.model,make_year=vehicle.makeyear, to_date__gte = today.date(),display_to="Lead")
                            print("QQQQQQQ1",var2)
                            for v in var2:
                                obj.append(model_to_dict(v))
                        #if groupname == "All":
                        try:
                            allpromo=Promotions.objects.filter(member=lead_obj.member,company=vehicle.company,model_id=vehicle.model,make_year=vehicle.makeyear, to_date__gte = today.date(),display_to="All")
                            print("QQQQQQQ2",allpromo)
                            for f in allpromo:
                                obj.append(model_to_dict(f))
                        except Exception as e:
                            pass
                            print("no promotion for ALL")
                com=Company.objects.get(company_name='All')

promotion/templates/promotion/promotions_detail.html
          		<td >{{ object.Service_id }}</td><br>
          		<td>{{ object.model_id }}</td><br>
          		<td>{{ object.make_year }}</td><br>
          		<td>{{object.coupon_code}}</td><br>
          		<td >{{ object.description }}</td><br>
          		
          		</tr>
         

promotion/templates/promotion/promotions_form.html
{% extends "base2.html" %}
{% load static from staticfiles %}
{% load i18n %}

{% block head %}
<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'js/validation/promo_validation.js' %}"></script>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
 

<script type='text/javascript'>
$(function() {
 
 
    $('#id_member').change(function() {
        // if changed to, for example, the last option, then
        // $(this).find('option:selected').text() == D
        // $(this).val() == 4
        // get whatever value you want into a variable
        var x = $(this).val();
        // and update the hidden input's value
        $('#myhidden').val(x);
    });
});
</script>
 <script type="text/javascript">
$(document).ready(function(){
	$("#promo").click(function(){
		 var fileUpload = $("#id_image");
		 var str = fileUpload.val();
    	 //alert("upload data"+fileUpload.val());
		 var n = str.endsWith(".jpg");
		 var m = str.endsWith(".png");
		// var p= str.endswith(".PNG");
		 flag=true;

		 
			
	     if (str != "")
	 {
			 if (n||m)
				 {
				 $("#lblError").hide();
				// document.getElementById('lblError').innerHTML="File format correct";
				// alert("file format correct");
				 flag=true;
				 }
			 else{
				 document.getElementById('lblError').innerHTML="Please upload file in '.jpg' or '.png' format only";
				// alert("file format is not correct");
				 flag=false;
			 }
			 }
		return flag;
	});
});
</script>
<style>
a: hover{

text-decoration:none !important;
}
</style>
<script>
$(document).ready(function(){
var total_amt=$("#id_total_amount").val();
	 if (total_amt==""){
		 $("#id_total_amount").val(0);
	 }
	 else{
	 $("#id_total_amount").val(total_amt);
	 }

  var text = "";
     var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

    for( var i=0; i < 4; i++ )
       text += possible.charAt(Math.floor(Math.random() * possible.length));
    var c=$("#id_discount").val();
  
    //alert(c);
    var d="AXN";
    d=d+text+c;
    $("#id_coupon_code").val(d);
	  $('#id_discount').keyup(function() {
	 var price=$("#id_price").val();
	 var discount=$("#id_discount").val();
	disc=price*(discount/100)
	total_amount=price-disc
	if( total_amount % 1 > 0.5 ) {
		total_amount = Math.round(total_amount);
		$("#id_total_amount").val(total_amount);
    }
	else{
		int_total_amount=Math.floor(total_amount)
		$("#id_total_amount").val(int_total_amount);
	}
	
	
	  });
	  $('#id_price').keyup(function() {
			 var price=$("#id_price").val();
			 var discount=$("#id_discount").val();
			disc=price*(discount/100)
			total_amount=price-disc
			if( total_amount % 1 > 0.5 ) {
				total_amount = Math.round(total_amount);
				$("#id_total_amount").val(total_amount);
		    }
			else{
				int_total_amount=Math.floor(total_amount)
				$("#id_total_amount").val(int_total_amount);
			}
			
			
			  });
			  
	 
		
	
});
</script>
<script>

$(document).ready(function(){
 $("#id_company>option[value='184']").insertAfter("#id_company>option[value='']")
    $("#id_make_year>option[value='28']").insertAfter("#id_make_year>option[value='']") 
 if($('#edit').val()=='edit'){
  //alert('hi');
  var service=$("#id_Service_id option:selected").val();
  
 }
 else{
  var delay = (function(){
     var timer = 0;
     return function(callback, ms){
     clearTimeout (timer);
     timer = setTimeout(callback, ms);
    };
   })();
  $("#id_discount").show();
  $("#id_price").show();
  $('#id_discount').keyup(function() {
           delay(function (){
            
            //alert("new");
            var service=$("#id_Service_id option:selected").val();
     // alert(service);
      if(service!=25)
      {
       
       var text = "";
            var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

           for( var i=0; i < 4; i++ )
              text += possible.charAt(Math.floor(Math.random() * possible.length));
           var c=$("#id_discount").val();
         
           //alert(c);
           var d="AXN";
           d=d+text+c;
        //alert(d);
      
         
            $("#id_coupon_code").val(d);
      
      }
     
           }, 1000 );
  });
  
  
  /* $('#id_price').keyup(function() {
           delay(function (){
            
            //alert("new");
            var service=$("#id_Service_id option:selected").val();
      //alert(service);

       //alert("else")
       var text = "";
          var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

          for( var i=0; i < 4; i++ )
              text += possible.charAt(Math.floor(Math.random() * possible.length));
          var c=$("#id_price").val();
          
          //alert(c);
          var d="AXN";
          d=d+text+c;
          //alert(d);
          $("#id_coupon_code").val(d);
       
           }, 1000 );
  });
   */
  
  //$("#id_make_year").children().detach().remove();
  
  
 }
 
 $("#id_member").attr("type","hidden");
 
 
 $("#id_company").attr("class","form-control");
 $("#id_model_id").attr("class","form-control");
 $("#id_make_year").attr("class","form-control");
 $("#id_Service_id").attr("class","form-control");
 $("#id_discount").attr("class","form-control");
 $("#id_description").attr("class","form-control");
 $("#id_from_date").attr("class","form-control");
 $("#id_to_date").attr("class","form-control");
 $("#id_coupon_code").attr("class","form-control");
 $("#id_price").attr("class","form-control");
 $("#id_coupon_code").prop("readonly", true);
 $("#id_total_amount").attr("class","form-control").prop("readonly", true);
 
 
 
 
 dict=null;
    $("#id_company" ).change(function() {
var op=$('option:selected', $(this)).text();
  //alert(op);
 
            $.ajax({
            url : '/promotion/test',
            type : "GET",
            data:{companyid : $('option:selected', $(this)).val()}
                }).done(function(data) {
                //alert(data);
    dict=data;
                $('#id_model_id').prop("disabled", false);
                $('#id_model_id').empty();
                $('#id_model_id').append('<option value="Please Select">Please Select</option>');
                for (var i = 0; i < data.length; i++)
                    {           
                 $('#id_model_id').append('<option value="'+data[i].id+'">'+data[i].model_name+'</option>');
            }  });
         $("#id_model_id" ).change(function() {

                var mod=$("#id_model_id option:selected").text();
              //  alert("model "+mod);
                if (mod=="All"){
                    $("#id_make_year").val(28);
                }
                });     

            

    });
    
    
    });
</script>

<script>
  $(function() {
     $( "#id_from_date" ).datepicker({minDate:0,dateFormat:'dd/mm/yy'});
});
  </script>
  
  <script>
  $(function() {
 $( "#id_to_date" ).datepicker({minDate:0,dateFormat:'dd/mm/yy'});
});
  
  </script>
  <style>
.page-header {
    padding-bottom: 9px;
    margin:-18px 0 20px !important;
    border-bottom: 1px solid #eee;
}
.seperator{
border-top: 4px solid #F38619;

}
.active_class{
color:#f38619;
}
</style>

<script>
 //var status=validate();
 //if (status==true)
// {
 //alert("success");
  //  $('#promoform').submit();
    //}

</script>

{% endblock %}

{% block content %}
<br>
 <div class="page-header">
             <h4 class="" style="color: #6B748A; font-size: 17px;"><span class="glyphicon glyphicon-th-list"></span>
                 PROMOTION FORM</h4>

        </div> 

 <div class="row"style="margin-right: 0px;margin-left:0px;">   
                
              
          <div class="dropdown pull-right">
          <a href="{%  url 'promotion:server_list_mem'  %}" style="text-decoration:none;">
            <button type="button" class="btn btn-primary " data-dismiss="modal">
               <i class="fa fa-reply" aria-hidden="true">
               </i> Back</button>
           </a>
             <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown">
               <i class="fa fa-floppy-o"></i> Save
                <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                       <li><a id="promo" type="submit"style="cursor: pointer;"><i class="fa fa-check" aria-hidden="true"></i> Save and Exit</a></li>
                   </ul>
             </div>
</div>
<input type="hidden" id="group" value="{{group.name}}">
<input type="hidden" id="edit" value="{{edit}}">
<div class="contain">   
    <div class="promotion" >      	    
	  <form class="form-horizontal" action='' method="POST" id="promo_form" enctype="multipart/form-data">{% csrf_token %}
        <fieldset>
        		    
			<div class="form-group">
			    <label class="col-md-4 control-label" for="id_company">Promotion for*:</label>  
			     <div class="col-md-4">
			         {{form.display_to}}
			         <span class="help-block"> </span>  
			    </div>
			</div>

       
			<div class="form-group">
			    <label class="col-md-4 control-label" for="id_company">Make*:</label>  
			     <div class="col-md-4">
			         {{form.company}}<div id="error1" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group">
			    <label class="col-md-4 control-label" for="model_id">Model*:</label>  
			     <div class="col-md-4">
			        {{form.model_id}}<div id="error2" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group">
			    <label class="col-md-4 control-label" for="id_make_year">Year*:</label>  
			     <div class="col-md-4">
			       {{form.make_year}}<div id="error3" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group">
			    <label class="col-md-4 control-label" for="id_company">Service Type*:</label>  
			     <div class="col-md-4">
			        {{form.Service_id}}<div id="error4" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group"id="price">
			    <label class="col-md-4 control-label" for="model_id">Price*:</label>  
			     <div class="col-md-4">
			        {{form.price}}<div id="error9" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group"id="discount">
			    <label class="col-md-4 control-label" for="model_id">Discount:</label>  
			     <div class="col-md-4">
			      {{form.discount}}  <div id="error5" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group">
			    <label class="col-md-4 control-label" for="id_make_year">Description*:</label>  
			     <div class="col-md-4">
			       {{form.description}}<div id="error6" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group">
			    <label class="col-md-4 control-label" for="id_company">From Date*:</label>  
			     <div class="col-md-4">
			       {{form.from_date}}<div id="error7" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group">
			    <label class="col-md-4 control-label" for="model_id">To Date*:</label>  
			     <div class="col-md-4">
			      {{form.to_date}}<div id="error8" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group">
			    <label class="col-md-4 control-label" for="model_id">Add image:</label>  
			     <div class="col-md-4">
			    {{form.image}}<div id="error8" style="color:red"></div>
			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group">
			    <label class="col-md-4 control-label" for="id_coupon_code">Coupon Code*:</label>  
			     <div class="col-md-4">
			  {{form.coupon_code}}
			         <span class="help-block"> </span>  
			    </div>
			</div>
			<div class="form-group">
			    <label class="col-md-4 control-label" for="id_total_amount">Total Amount:</label>  
			     <div class="col-md-4">
			  {{form.total_amount}}
			         <span class="help-block"> </span>  
			    </div>
			</div>
       
		    <div class="form-group">
		      <!-- Button -->
		      <div class="controls">
		        
		      </div>
		    </div>
       </fieldset>
    </form>  
 </div>
</div>
{% endblock %}